
title: Jordan Hay
url: https://jordanhay.com

timezone: Pacific/Auckland

collections:
  articles:
    output: true
    permalink: /:collection/:year/:month/:title
  projects:
    output: true
    permalink: /:collection/:name