
title: Jordan Hay
url: https://jordanhay.com
author: Jordan Hay

timezone: Pacific/Auckland

plugins:
 - jekyll-feed

collections:
  articles:
    output: true
    permalink: /:collection/:year/:month/:title
    sort_by: date
  archive:
    output: true
    permalink: /:collection/:year/:month/:title
    sort_by: date

defaults:
  -
    scope:
      path: ""
      type: "articles"
    values:
      layout: "article" 
  - 
    scope:
      path: ""
      type: "archive"
    values:
      layout: "article"

feed:
  icon: /img/logo.png
  posts_limit: 20
  collections:
   - articles
