
title: Jordan Hay
url: https://jordanhay.com

timezone: Pacific/Auckland

collections:
  articles:
    output: true
    permalink: /:collection/:year/:month/:title
    sort_by: date
  projects:
    output: true
    permalink: /:collection/:name
    sort_by: date
  archive:
    output: true
    permalink: /:collection/:year/:month/:title
    sort_by: date

defaults:
  -
    scope:
      path: ""
      type: "articles"
    values:
      layout: "article" 
  - 
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - 
    scope:
      path: ""
      type: "archive"
    values:
      layout: "article"